### ISSUE TITLE
Create binder

### ISSUE THREAD

**Issue by samreid** [phetsims/binder#1]

**Comment by zepumph** [comment]
@samreid I never got your second commit, so I just went for it on my own. Notice that my file is not in the js dir, and I think it is named differently from yours. I recommend copying my contents into your file (change the path to perennial), and from there work to get the global content from the sim (that's your speciality) returned in the `resolve` call of the promise. Good luck!

**Comment by samreid** [comment]
Initial commit is above, spanning several repos.  To use this, you will need to npm install the following npm modules: 

* puppeteer 
* marked

To run it, 
```
cd binder/js
node generateDocumentation.js html.html
```

Or you can specify a subset of sims to use:
```
node generateDocumentation.js html.html wave-on-a-string,acid-base-solutions,concentration
```

This process also creates a JSON file binderjson.json which can be used to render the HTML directly (if you don't want to iterate through the sims again).

```
node createReportFromData.js json binderjson.json > html.html
```

**Comment by zepumph** [comment]
@samreid I updated this, trying to simplify the code as much as possible. I added some logging and documentation, removed your 'console' based query parameter. The main thing I did was transfer the logic around getting the `InstanceRegistry.map` to a "loaded" `postMessage` from the console.log message. Otherwise I'm Liking what we are working toward. 

Next steps/improvements
* It could be nice to have this run async, and launch multiple pages at once, that would make things run faster.
* We can start to bring in other modules, like stuff involving the website metadata.
* There are a lot of "duplicate" components, maybe we can wean things out?

@samreid let's talk about next steps soon, maybe we can show this off this afternoon.

**Comment by zepumph** [comment]
@samreid on windows, I get the following error when regenerating the html from the json:
```
 Michael /e/zepumph/Programming/PHET/git/binder/js (master)
 $ node createReportFromData.js json binderjson.json > html.html
stdout is not a tty

```

**Comment by zepumph** [comment]
I think that the documentation has been created, and can be viewed https://phetsims.github.io/binder/.

Closing

**Comment by pixelzoom** [comment]
@samreid FYI, query parameters are (by convention) listed in alphabetical order in initialize-globals.js.  I've relocated `binder` in the above commit.

**Comment by pixelzoom** [comment]
We agreed in a recent dev meeting to indicate whether query parameters are public facing or for internal use only. Please indicate for binder.

**Comment by samreid** [comment]
Thanks for letting me know about the alphabetization.  I assigned to @mbarlow12 for documenting it.

**Comment by mbarlow12** [comment]
Updated the param doc in `initialize-globals.js`. Closing.
