### ISSUE TITLE
Add fast html compile option from generated json instead of sim instance registry

### ISSUE THREAD

**Issue by mbarlow12** [phetsims/binder#14]
Since we generate a json doc anyway when accessing the sims, a quick way to regenerate the html file will be very useful. Perhaps a new npm/grunt task?

**Comment by samreid** [comment]
If I'm understanding you correctly, binder used to do that.  @zepumph can you comment?

**Comment by zepumph** [comment]
Yes indeed! In the readme there are steps to do just this:
```
The generated docs load sim to gather runtime information. To bypass this step and use stored data from sim loads:

`cd js/; node createHTMLString.js json binderjson.json > html.html`
```
But that is pretty sloppy, and I agree could use some scaffolding. @mbarlow12 I would recommend looking at the logic behind `binderjson.json` and going from there.

**Comment by mbarlow12** [comment]
I had intended to just clean up the existing implementation and add make the command to generate it a little cleaner—maybe something like `npm run build-from-json` that would generate the docs/index.html and compile any necessary css/js assets that we add in the future.

**Comment by zepumph** [comment]
Do you think that this could benefit from using grunt, so far this is two separate tasks, and we may way option support for both of them. In the installer builder, it started out as just one task, and so I thought grunt was a bit overkill, but I sorta wish I had gone that direction because I then had to add my own parsing and support (help/etc) for 10+ options. 

One question about that is if you could integrate some of chipper's build tasks (like lint) into this grunt file. I don't see why not, just a thought though.

**Comment by mbarlow12** [comment]
As of now, this is implemented with an npm task. In the top level of `binder`, simply run `npm run build-json` to regenerate the html and pull markdown from the various sim `doc/` directories.
